//---------//
// IMPORTS //
//---------//

local bundle = import 'lib/bundle.libsonnet';
local file_paths = import 'lib/file_paths.libsonnet';
local k = import 'lib/karabiner.libsonnet';

local unless_hypervisor_ide_remoteDesktop_terminalEmulator = k.condition(
  'unless',
  bundle.hypervisors + bundle.ides + bundle.remoteDesktops + bundle.terminalEmulators,
  file_paths.remoteDesktops
);

local unless_hypervisor_ide_remoteDesktop = k.condition(
  'unless',
  bundle.hypervisors + bundle.ides + bundle.remoteDesktops,
  file_paths.remoteDesktops
);

local unless_remoteDesktop_hypervisor = k.condition(
  'unless',
  bundle.hypervisors + bundle.remoteDesktops,
  file_paths.remoteDesktops
);

// Windows word-motion + plain-Ctrl+V paste fire in normal apps AND the VS Code family
// (the Claude Code panel + editor, and -- best effort -- VS Code's integrated terminal),
// translating Ctrl+arrow -> Option+arrow and Ctrl+V -> Cmd+V for inputs that honour Mac
// motion but ignore raw Ctrl. They are DELIBERATELY excluded from SYSTEM terminal emulators
// (Terminal.app/Ghostty): those stay PURE LINUX -- raw Ctrl reaches the shell/Claude TUI
// where readline + shell/macboard.zsh handle word-motion exactly as on Linux, and plain
// Ctrl+V stays quoted-insert (paste is Ctrl+Shift+V). Remote desktops + hypervisors keep
// raw Ctrl too (they're literally Windows). Ctrl+C/X/Z/A copy/cut/undo/select-all live in
// the separate VS Code-family rules; Ctrl+Shift+C/V + Ctrl/Shift+Insert handle terminals.
local unless_systemTerminal = k.condition(
  'unless',
  bundle.terminalEmulators + bundle.remoteDesktops + bundle.hypervisors,
  file_paths.remoteDesktops
);

// Terminal-style copy/paste belongs in every terminal-LIKE surface: real terminal
// emulators AND Claude Code's IDE panel + the VS Code integrated terminal. There Ctrl+C
// is reserved for interrupt, so copy/paste shift up to Ctrl+Shift+C/V and Ctrl/Shift+Insert
// (the Linux-terminal convention). Normal apps don't need it -- they copy with plain Ctrl+C.
local if_terminal_or_ide = k.condition('if', bundle.terminalEmulators + bundle.ides);

// The VS Code family hosts the Claude Code panel, whose webview input can't be reached by
// VS Code's own keybindings -- so we give it the full Windows edit cluster (Ctrl+C copy,
// Ctrl+X cut, Ctrl+Z/Shift+Z undo/redo, Ctrl+A select-all) at the Karabiner layer. Scoped
// to VS Code/Cursor ONLY (not the wider `ides` bundle): Karabiner can't tell the panel
// from VS Code's integrated terminal, so this DOES cost Ctrl+C=interrupt there -- the user
// runs shells in standalone terminal emulators (Terminal.app/Ghostty), where Ctrl+C stays
// raw, so that trade is accepted. Ctrl+V paste is already handled by ide_terminal_safe.
local if_vscode_family = k.condition('if', bundle.vscodeFamily);

//------//
// MAIN //
//------//

{
  title: 'Windows Shortcuts',
  rules: [
    k.rule('Insert (Ctrl)',
           k.input('insert', ['control']),
           k.outputKey('c', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Insert (Shift)',
           k.input('insert', ['shift']),
           k.outputKey('v', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Home (Ctrl+Shift)',
           k.input('home', ['control', 'shift']),
           k.outputKey('up_arrow', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Home (Shift)',
           k.input('home', ['shift']),
           k.outputKey('left_arrow', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Home (Ctrl)',
           k.input('home', ['control']),
           k.outputKey('up_arrow', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Home',
           k.input('home'),
           k.outputKey('left_arrow', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('End (Ctrl+Shift)',
           k.input('end', ['control', 'shift']),
           k.outputKey('down_arrow', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('End (Shift)',
           k.input('end', ['shift']),
           k.outputKey('right_arrow', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('End (Ctrl)',
           k.input('end', ['control']),
           k.outputKey('down_arrow', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('End',
           k.input('end'),
           k.outputKey('right_arrow', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Left Arrow (Ctrl)',
           k.input('left_arrow', ['control']),
           k.outputKey('left_arrow', ['option']),
           unless_systemTerminal),
    k.rule('Left Arrow (Ctrl+Shift)',
           k.input('left_arrow', ['control', 'shift']),
           k.outputKey('left_arrow', ['option', 'shift']),
           unless_systemTerminal),
    k.rule('Right Arrow (Ctrl)',
           k.input('right_arrow', ['control']),
           k.outputKey('right_arrow', ['option']),
           unless_systemTerminal),
    k.rule('Right Arrow (Ctrl+Shift)',
           k.input('right_arrow', ['control', 'shift']),
           k.outputKey('right_arrow', ['option', 'shift']),
           unless_systemTerminal),
    k.rule('Backspace (Ctrl)',
           k.input('delete_or_backspace', ['control']),
           k.outputKey('delete_or_backspace', ['option']),
           unless_systemTerminal),
    k.rule('Delete (Ctrl)',
           k.input('delete_forward', ['control']),
           k.outputKey('delete_forward', ['option']),
           unless_systemTerminal),
    k.rule('Enter (Ctrl)',
           k.input('return_or_enter', ['control']),
           k.outputKey('return_or_enter', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Enter (Ctrl+Shift)',
           k.input('return_or_enter', ['control', 'shift']),
           k.outputKey('return_or_enter', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('A (Ctrl)',
           k.input('a', ['control']),
           k.outputKey('a', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('B (Ctrl)',
           k.input('b', ['control']),
           k.outputKey('b', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('C (Ctrl)',
           k.input('c', ['left_control']),
           k.outputKey('c', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('F (Ctrl)',
           k.input('f', ['control']),
           k.outputKey('f', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('I (Ctrl)',
           k.input('i', ['control']),
           k.outputKey('i', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('N (Ctrl)',
           k.input('n', ['control']),
           k.outputKey('n', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('O (Ctrl)',
           k.input('o', ['control']),
           k.outputKey('o', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('P (Ctrl)',
           k.input('p', ['control']),
           k.outputKey('p', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('R (Ctrl)',
           k.input('r', ['control']),
           k.outputKey('r', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('S (Ctrl)',
           k.input('s', ['control']),
           k.outputKey('s', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('T (Ctrl)',
           k.input('t', ['control']),
           k.outputKey('t', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('U (Ctrl)',
           k.input('u', ['control']),
           k.outputKey('u', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('V (Ctrl)',
           k.input('v', ['control']),
           k.outputKey('v', ['command']),
           unless_systemTerminal),
    k.rule('W (Ctrl)',
           k.input('w', ['control']),
           k.outputKey('w', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('X (Ctrl)',
           k.input('x', ['control']),
           k.outputKey('x', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Y (Ctrl)',
           k.input('y', ['control']),
           k.outputKey('y', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Z (Ctrl)',
           k.input('z', ['control']),
           k.outputKey('z', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('Space (Ctrl)',
           k.input('spacebar', ['control']),
           k.outputKey('spacebar', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('F1',
           k.input('f1'),
           k.outputKey('slash', ['command', 'shift']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    k.rule('F3',
           k.input('f3'),
           k.outputKey('g', ['command']),
           unless_hypervisor_ide_remoteDesktop_terminalEmulator),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('1 (Cmd) [Open first pinned Dock app (Finder); +IDEs and Terminal Emulators]',
           k.input('1', ['command']),
           k.outputShell('open -b com.apple.finder'),
           unless_remoteDesktop_hypervisor),
    k.rule('2 (Cmd) [Open second pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('2', ['command']),
           k.runDockedApp('0'),
           unless_remoteDesktop_hypervisor),
    k.rule('3 (Cmd) [Open third pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('3', ['command']),
           k.runDockedApp('1'),
           unless_remoteDesktop_hypervisor),
    k.rule('4 (Cmd) [Open fourth pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('4', ['command']),
           k.runDockedApp('2'),
           unless_remoteDesktop_hypervisor),
    k.rule('5 (Cmd) [Open fifth pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('5', ['command']),
           k.runDockedApp('3'),
           unless_remoteDesktop_hypervisor),
    k.rule('6 (Cmd) [Open sixth pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('6', ['command']),
           k.runDockedApp('4'),
           unless_remoteDesktop_hypervisor),
    k.rule('7 (Cmd) [Open seventh pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('7', ['command']),
           k.runDockedApp('5'),
           unless_remoteDesktop_hypervisor),
    k.rule('8 (Cmd) [Open eighth pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('8', ['command']),
           k.runDockedApp('6'),
           unless_remoteDesktop_hypervisor),
    k.rule('9 (Cmd) [Open ninth pinned Dock app; +IDEs and Terminal Emulators]',
           k.input('9', ['command']),
           k.runDockedApp('7'),
           unless_remoteDesktop_hypervisor),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('Win [Open Spotlight] [Always]',
           k.input('left_command', key_is_modifier=true),
           [
             k.outputKey('left_command', output_type='to'),
             k.outputKey('spotlight', output_type='to_if_alone', key_code='apple_vendor_keyboard_key_code'),
           ]),
    k.rule('L (Win) [Lock Screen] [Always]',
           k.input('l', ['command']),
           k.outputKey('q', ['control', 'command'])),
    k.rule('L (Win) [Sleep] [Always]',
           k.input('l', ['command']),
           k.outputKey('power', ['control', 'shift'])),
    k.rule('L (Alt+Ctrl) [Lock Screen] [Always]',
           k.input('l', ['control', 'option']),
           k.outputKey('q', ['control', 'command'])),
    k.rule('L (Alt+Ctrl) [Sleep] [Always]',
           k.input('l', ['control', 'option']),
           k.outputKey('power', ['control', 'shift'])),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('Insert (Ctrl) [+Terminal Emulators + IDEs]',
           k.input('insert', ['control']),
           k.outputKey('c', ['command']),
           if_terminal_or_ide),
    k.rule('Insert (Shift) [+Terminal Emulators + IDEs]',
           k.input('insert', ['shift']),
           k.outputKey('v', ['command']),
           if_terminal_or_ide),
    k.rule('/ (Ctrl) [+Terminal Emulators]',
           k.input('slash', ['control']),
           k.outputKey('slash', ['command']),
           unless_hypervisor_ide_remoteDesktop),
    k.rule('F4 (Alt) [+Terminal Emulators]',
           k.input('f4', ['option']),
           k.outputKey('q', ['command']),
           unless_hypervisor_ide_remoteDesktop),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('C (Ctrl+Shift) [Terminal Emulators + IDEs]',
           k.input('c', ['control', 'shift']),
           k.outputKey('c', ['command']),
           if_terminal_or_ide),
    k.rule('V (Ctrl+Shift) [Terminal Emulators + IDEs]',
           k.input('v', ['control', 'shift']),
           k.outputKey('v', ['command']),
           if_terminal_or_ide),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Windows edit cluster for the Claude Code panel (VS Code family only). Ctrl+V paste is
    // already covered by ide_terminal_safe; these add copy/cut/undo/redo/select-all.
    k.rule('C (Ctrl) [Only VS Code family -> copy in the Claude Code panel]',
           k.input('c', ['control']),
           k.outputKey('c', ['command']),
           if_vscode_family),
    k.rule('X (Ctrl) [Only VS Code family]',
           k.input('x', ['control']),
           k.outputKey('x', ['command']),
           if_vscode_family),
    k.rule('Z (Ctrl) [Only VS Code family]',
           k.input('z', ['control']),
           k.outputKey('z', ['command']),
           if_vscode_family),
    k.rule('Z (Ctrl+Shift) [Only VS Code family -> redo]',
           k.input('z', ['control', 'shift']),
           k.outputKey('z', ['command', 'shift']),
           if_vscode_family),
    k.rule('A (Ctrl) [Only VS Code family -> select all]',
           k.input('a', ['control']),
           k.outputKey('a', ['command']),
           if_vscode_family),
    // Home/End for the Claude Code editable text box (dead there natively). Mac-native line/
    // input motion; VS Code family only so Emacs/Kitty + system terminals keep raw Home/End.
    // MOST-SPECIFIC FIRST: bare Home/End match any extra modifiers, so the Ctrl/Shift
    // variants must precede them or they'd be shadowed.
    k.rule('Home (Ctrl+Shift) [Only VS Code family -> select to input start]',
           k.input('home', ['control', 'shift']),
           k.outputKey('up_arrow', ['command', 'shift']),
           if_vscode_family),
    k.rule('Home (Shift) [Only VS Code family -> select to line start]',
           k.input('home', ['shift']),
           k.outputKey('left_arrow', ['command', 'shift']),
           if_vscode_family),
    k.rule('Home (Ctrl) [Only VS Code family -> input start]',
           k.input('home', ['control']),
           k.outputKey('up_arrow', ['command']),
           if_vscode_family),
    k.rule('Home [Only VS Code family -> line start]',
           k.input('home'),
           k.outputKey('left_arrow', ['command']),
           if_vscode_family),
    k.rule('End (Ctrl+Shift) [Only VS Code family -> select to input end]',
           k.input('end', ['control', 'shift']),
           k.outputKey('down_arrow', ['command', 'shift']),
           if_vscode_family),
    k.rule('End (Shift) [Only VS Code family -> select to line end]',
           k.input('end', ['shift']),
           k.outputKey('right_arrow', ['command', 'shift']),
           if_vscode_family),
    k.rule('End (Ctrl) [Only VS Code family -> input end]',
           k.input('end', ['control']),
           k.outputKey('down_arrow', ['command']),
           if_vscode_family),
    k.rule('End [Only VS Code family -> line end]',
           k.input('end'),
           k.outputKey('right_arrow', ['command']),
           if_vscode_family),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('H (Ctrl) [Only Web Browsers]',
           k.input('h', ['control']),
           k.outputKey('y', ['command']),
           k.condition('if', bundle.webBrowsers)),
    k.rule('L (Ctrl) [Only Web Browsers]',
           k.input('l', ['control']),
           k.outputKey('l', ['command']),
           k.condition('if', bundle.webBrowsers)),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    k.rule('F4 (Ctrl) [Only Chrome]',
           k.input('f4', ['control']),
           k.outputKey('w', ['command']),
           k.condition('if', ['^com\\.google\\.Chrome$', '^com\\.google\\.chrome$'])),
    k.rule('F5 [Only Chrome]',
           k.input('f5'),
           k.outputKey('r', ['command']),
           k.condition('if', ['^com\\.google\\.Chrome$', '^com\\.google\\.chrome$'])),
    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Alt+Tab (Option+Tab) is intentionally LEFT RAW -- no rule. It passes straight through to the
    // AltTab app (installed by install.sh) on its default Option+Tab trigger, giving Windows-style
    // per-WINDOW switching. The previous Option+Tab -> Cmd+Tab remap fired macOS's native per-APP
    // switcher instead, so AltTab never saw the key. AltTab also needs continuously-held modifiers,
    // which a discrete Karabiner chord can't provide -- another reason not to remap it.
    // (For RDP: add the client to AltTab's Exceptions so Alt+Tab reaches the remote session.)
  ],
}
